service: serverless-graphql

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  graphql:
    handler: graphql.handler
    events:
      - http:
          path: graphql
          method: post
  playground:
    handler: graphql.handler
    events:
      - http:
          path: playground
          method: get
